### PR TITLE
Create 2015-11-24-Spark-Scala-Tutorial.md

### PR DESCRIPTION
**Pull request by helenahm**
Hi Matthew,

Here is a slightly modified java-spark article into a scala-spark article, i think maybe it is best to leave it like that as i talked a little bit here about history of Spark and RDDs. It is best to modify Java-Spark to substitute this parts by describing differences between Java and Spark variants of the same code maybe?

Regards,
Elena.

### CODE REVIEW

**Comment by rathboma** [comment]
Hey,

I think this looks great!

One question I think we need to answer in the post - when does Spark _actually_ submit operations to the cluster?

Specifically manipulating RDD's to make other RDDs doesn't actually do anything until a computation is called. In this case it seems like calling `countByKey` initiates the computation.

I'd highlight this by referring to the spark docs on transformations vs actions:
http://spark.apache.org/docs/latest/programming-guide.html#transformations

From what I can gather Transformations convert an RDD into another RDD (so nothing is computed), and actions cause computations and return actual results? Is that correct?

**Comment by rathboma** [comment]
Regarding the Java article - yes, let's change it to refer to the Scala article and talk about the differences in the Java API vs the Scala API.

**Comment by helenahm** [comment]
Hi Matthew,
I have added_posts/2015-11-30-Spark-Java-Tutorial.md
to the Spark-Scala Tutorials pull request.

Will look at the code comments now,Regards,Elena.

```
On Wednesday, 25 November 2015, 19:57, Matthew Rathbone <notifications@github.com> wrote:
```

 Regarding the Java article - yes, let's change it to refer to the Scala article and talk about the differences in the Java API vs the Scala API.—

**Comment by helenahm** [comment]
Hi Matthew,

i will add something about "when does Spark actually submit operations to the cluster?" to the articles now, you are right, there is difference between actions and transformations, and it is easy to see in CLI that only countByKey triggers some real action, other pieces of code result in a notification about creating an output of such and such format, but do not seem to do anything.
This article and some other ones support this understanding:
https://dzone.com/articles/big-data-processing-spark

Regards,
Elena.

**Comment by helenahm** [comment]
Hi again,

I have added two extra paragraphs to draw attention of a reader to the difference between actions and transformations. 

Now, you have two articles Java and Scala and two versions of code, 2 for Scala and 2 for Java. 

Does any of the versions of the code corresponds to what you meant in your comments? Shall I put a newer version of the code to the article(s)?

Regards,
Elena.

**Pull request merged**
